import { PERMISSIONS } from '@schoolos/config';

export const STUDENTS_PERMISSIONS = {
  read: PERMISSIONS.STUDENTS_PROFILE_READ,
  create: PERMISSIONS.STUDENTS_PROFILE_CREATE,
  update: PERMISSIONS.STUDENTS_PROFILE_UPDATE,
  delete: PERMISSIONS.STUDENTS_PROFILE_DELETE,
  bulkImport: PERMISSIONS.STUDENTS_BULK_IMPORT,
} as const;
