import { PERMISSIONS } from '@schoolos/config';
export const CLASS_SECTION_PERMISSIONS = {
  manage: [PERMISSIONS.ACADEMICS_CLASS_SECTION_MANAGE],
  read: [PERMISSIONS.ACADEMICS_CLASS_READ],
  teacherAssign: [PERMISSIONS.ACADEMICS_TEACHER_ASSIGNMENT_MANAGE],
} as const;
