import { PERMISSIONS } from '@schoolos/config';

export const YEAR_PERMISSIONS = {
  create: [PERMISSIONS.ACADEMICS_YEAR_MANAGE],
  read: [PERMISSIONS.ACADEMICS_CLASS_READ],
  update: [PERMISSIONS.ACADEMICS_YEAR_MANAGE],
  delete: [PERMISSIONS.ACADEMICS_YEAR_MANAGE],
  setCurrent: [PERMISSIONS.ACADEMICS_YEAR_MANAGE],
} as const;
